### PR TITLE
Fix for Libdl moving to the stdlib

### LINKED ISSUE #78: build error on 0.7, Libdl not defined
```julia
julia> Pkg.build("HttpParser")
[ Info: Building HttpParser
┌ Warning: `is_windows` is deprecated, use `Sys.iswindows` instead.
│   caller = top-level scope
└ @ Core :0
┌ Warning: `is_unix` is deprecated, use `Sys.isunix` instead.
│   caller = top-level scope
└ @ Core :0
┌ Error: ------------------------------------------------------------
│ # Build failed for HttpParser
│   exception =
│    LoadError: UndefVarError: Libdl not defined
│    Stacktrace:
│     [1] top-level scope at /home/tamas/.julia/v0.7/HttpParser/deps/build.jl:38
│     [2] include at ./boot.jl:292 [inlined]
│     [3] include_relative(::Module, ::String) at ./loading.jl:521
│     [4] include at ./sysimg.jl:26 [inlined]
│     [5] include(::String) at ./loading.jl:555
│     [6] top-level scope
│     [7] eval at ./boot.jl:295 [inlined]
│     [8] eval at ./sysimg.jl:71 [inlined]
│     [9] evalfile(::String, ::Array{String,1}) at ./loading.jl:550 (repeats 2 times)
│     [10] #4 at ./none:12 [inlined]
│     [11] cd(::getfield(, Symbol("##4#7")){String}, ::String) at ./file.jl:70
│     [12] (::getfield(, Symbol("##3#5")))(::IOStream) at ./none:11
│     [13] open(::getfield(, Symbol("##3#5")), ::String, ::String) at ./iostream.jl:310
│     [14] top-level scope
│     [15] eval at ./boot.jl:295 [inlined]
│     [16] eval(::Module, ::Expr) at ./sysimg.jl:71
│     [17] process_options(::Base.JLOptions) at ./client.jl:301
│     [18] _start() at ./client.jl:375
│    in expression starting at /home/tamas/.julia/v0.7/HttpParser/deps/build.jl:38
└ @ Main none:15
┌ Warning: ------------------------------------------------------------
│ # Build error summary
│ 
│ HttpParser had build errors.
│ 
│  - packages with build errors remain installed in /home/tamas/.julia/v0.7
│  - build the package(s) and all dependencies with `Pkg.build("HttpParser")`
│  - build a single package by running its `deps/build.jl` script
└ @ Base.Pkg.Entry entry.jl:656
```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #78.

### CODE REVIEW

**Comment by aviks** [comment]
Tests seem to have failed on 0.7 on Appveyor: 

```
ERROR: LoadError: TypeError: in Type{...} expression, expected UnionAll, got typeof(Base.Nullable)
Stacktrace:
 [1] top-level scope
 [2] include(::Module, ::String) at .\boot.jl:292
 [3] include_relative(::Module, ::String) at .\loading.jl:521
 [4] include(::Module, ::String) at .\sysimg.jl:26
 [5] top-level scope
 [6] eval at .\boot.jl:295 [inlined]
 [7] top-level scope at .\<missing>:2
in expression starting at C:\Users\appveyor\.julia\v0.7\HttpCommon\src\HttpCommon.jl:65
ERROR: LoadError: Failed to precompile HttpCommon to C:\Users\appveyor\.julia\lib\v0.7\HttpCommon.ji.
Stacktrace:
```

**Comment by ararslan** [comment]
That's unrelated to this change. I _think_ fixing it just requires adding a dependency on Nullables.

**Comment by ararslan** [comment]
Weird, `Nullable` isn't used anywhere here, so I don't know why that would be happening...

**Comment by fp4code** [comment]
Indeed, even master is no more building on 0.7 https://travis-ci.org/fp4code/HttpParser.jl/builds/330168637
Please ararslan, restart building job to check that problem with actual julia-0.7

**Pull request closed without merging**
