### PR TITLE
Use Int and compat Dict, fix 0.4 deprecations.

### PR DESCRIPTION
**Pull request by hayd**

### CODE REVIEW

**Comment by IainNZ** [comment]
Yo @hayd does your editor add a blank line at the end of each file automatically?

**Comment by hayd** [comment]
I guess it does! Will see if I can correct that if it's an issue. :/

Does this need to be `@compat Int(...)` for 0.3?

**Comment by IainNZ** [comment]
Not sure, seems like it?

**Comment by IainNZ** [comment]
```julia
julia> using Compat

julia> Int(0x11)
ERROR: type cannot be constructed

julia> @compat Int(0x11)
17
```

**Comment by hayd** [comment]
fixed.

**Comment by tkelman** [comment]
should this be tagged at some point?

**Pull request merged**
