### PR TITLE
Bump http-parser version to 2.8.1

### LINKED ISSUE #75: HttpParser fails to build on recent ArchLinux and Julia Version 0.6.0 (2017-06-19 13:05 UTC)
A fix which seems to have worked for me was to comment out the -Werror switch in `~/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/Makefile` line 57:
```
CFLAGS += -Wall -Wextra #-Werror
```
Otherwise, a warning which stems from a drop through in `case 2:` below (line 1817  `~/.julia/v0.6/HttpParser/deps/src/http-parser-2.7.1/http_parser.c` is treated as an error and aborts the build. However, the drop through (missing break statement) in `case 2:` seems purposeful. I am guessing about that however.

```
        if (settings->on_headers_complete) {
          switch (settings->on_headers_complete(parser)) {
            case 0:
              break;

            case 2:
              parser->upgrade = 1;

            case 1:
              parser->flags |= F_SKIPBODY;
              break;

            default:
              SET_ERRNO(HPE_CB_headers_complete);
              RETURN(p - data); /* Error */
          }
        }
```

### PR DESCRIPTION
**Pull request by pabloferz**
The only missing bit here is updating the binary of the library for windows (but I don't have access to the server where it is stored).

This should supersede #82 and fix #75.

### CODE REVIEW

**Comment by pabloferz** [comment]
This now seems to pass on 0.6, but we would need some additional changes for this to pass on 0.7

**Comment by rdeits** [comment]
HttpParser.jl currently fails to build on a stock Ubuntu 18.04 install due to #75. This branch fixed it for me, so it would be great to get this merged if possible.

**Comment by pabloferz** [comment]
This passes tests on 0.6. I guess we could merge it and fix the 0.7 support later (which is not really related to these changes)

**Comment by pabloferz** [comment]
Oh right, I forgot I don't have access to the server where the windows binary is stored. Can someone (@staticfloat, @ararslan) upload the binary so we can merge this?

**Comment by staticfloat** [comment]
I don't know how to generate these binaries.  Who is the last person who did so?

**Comment by pabloferz** [comment]
Seems like it might have been @ranjanan

**Comment by ranjanan** [comment]
Yes, it was me. I shall cross compile and upload v2.8.1

**Comment by ranjanan** [comment]
Could you change [this line](https://github.com/JuliaWeb/HttpParser.jl/pull/85/files#diff-ed74277d7f2e98f12cf51e6b8be90705R67) to 2_8_1 please? I've uploaded the right windows libraries to s3. You can restart Appveyor and it should work

**Comment by pabloferz** [comment]
Everything seems to be working on 0.6, so I guess we can merge this (I'd do it myself but I don't have commit access in this organization) and work on fixing the package for 0.7 later.

**Pull request closed without merging**
